[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "konfucian"
version = "0.1.0"
description = "Common library for Konfusing CLIs. Confucian. Could be confusion."
readme = "README.md"
requires-python = ">=3.12"
license = {text = "GPLv3+"}
authors = [
    {name = "Adam Cmiel", email = "acmiel@redhat.com"},
]
dependencies = []
